services:
  postgres:
    image: postgres:15
    container_name: libris_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./${MIGRATIONS_DIR}:/${MIGRATIONS_DIR}
    entrypoint: [
      "migrate",
      "-path", "/${MIGRATIONS_DIR}",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}",
      "up"
    ]
  # server:
  #   build:
  #     context: .
  #   container_name: libris_server
  #   depends_on:
  #     migrate:
  #       condition: service_completed_successfully
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   environment:
  #     NAME: ${NAME}
  #     POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}
  #     SERVER_PORT: ${SERVER_PORT}
volumes:
  db_data: