services:
  postgres:
    image: postgres:15
    container_name: libris_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    container_name: libris_migrate
    image: migrate/migrate:latest
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path=${MIGRATIONS_PATH} -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE} up"
      ]
    volumes:
      - ${MIGRATIONS_PATH}:/migrations
  server:
    build:
      context: .
    container_name: libris_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - migrate
    command: [./server]
volumes:
  db_data: